### ISSUE TITLE
Fix curl command in Ariel sample

### ISSUE THREAD

**Issue by liherelgezabal** [IBM/qradar-sample-apps#38]
Hi team,

I found that for the Ariel sample at
https://github.com/IBM/qradar-sample-apps/tree/master/Ariel

the curl command does't work like this (because of the ./ in the js file name):
curl -LJ https://github.com/IBM/qjslib/releases/download/1.1.1/qjslib-1.1.1.tgz \
    | tar -xvzO ./package/lib/qappfw.min.js > ./app/static/qjslib/qappfw.min.js

This works for me instead:
curl -LJ https://github.com/IBM/qjslib/releases/download/1.1.1/qjslib-1.1.1.tgz \
    | tar -xvzO package/lib/qappfw.min.js > ./app/static/qjslib/qappfw.min.js

regards,
liher

**Comment by jthomperoo** [comment]
READMEs now updated, thanks for pointing this out!
